### ISSUE TITLE
InvalidLogError: Anomalous item quality:02

### ISSUE THREAD

**Issue by coopyey** [nivomi/RetainerMaintainer#1]
[Here's an image of the error that it gave me!](https://i.imgur.com/V1Ko8jx.png
)

I have attached my network log that has caused this error as well, for your reference. I should mention that my retainers have a mixture of crafting items in addition to clothes - not sure if that caused the issue, and I do have relic weapons stored in one of my retainers.

[Network_20180202.log](https://github.com/nivomi/RetainerMaintainer/files/1690215/Network_20180202.log)

**Comment by Ikuni17** [comment]
I got a similar error:
[Image](https://i.imgur.com/sWyylen.png)

[Network_20180202.log](https://github.com/nivomi/RetainerMaintainer/files/1690324/Network_20180202.log)

**Comment by nivomi** [comment]
Thank you for the reports - this particular issue should be fixed. Sorry for the inconvenience!
